---
- hosts: apic
  connection: local
  gather_facts: no

  vars:
    apic_info: &apic_info
      host:           "{{ ansible_host }}" 
      user:           "{{ ansible_user }}" 
      password:       "{{ ansible_password }}" 
      validate_certs: "{{ validate_certs }}"
      use_ssl:        "{{ use_ssl }}"
    
    alert_sender: CHANGE_ME

  tasks:
    - name: "TASK_1 - 인터페이스 정보 수집"
      cisco.aci.aci_rest:
        <<: *apic_info
        path:   "/api/class/ethpmPhysIf.json"
        method: "get"
      register: ethpmPhysIf
        
    - name: "TASK_2 - 인터페이스 정보 중, oper down 확인"
      set_fact:
        interface_down: "{{ ethpmPhysIf | json_query('imdata[].ethpmPhysIf.attributes') | json_query('[?operSt!=`up`]') }}"

    - name: "TASK_3 - 인터페이스 oper state down 없으면 play 종료"
      ansible.builtin.meta: end_play
      when: interface_down | length == 0

    - name: "TASK_4 - CSV 파일 생성"
      copy:
        content: |
          POD,Node,Interface,Mode,Speed,Status
          {% for item in interface_down %}
          {% set pod       = item.dn.split("/")[1].split("-")[1] %}
          {% set node      = item.dn.split("/")[2].split("-")[1] %}
          {% set ethPre    = item.dn.split("/")[4].split("-")[1] %}
          {% set ethPost   = item.dn.split("/")[5] %}
          {% set operMode  = item.operMode %}
          {% set operSpeed = item.operSpeed %}
          {% set operSt    = item.operSt %}
          {{ pod }},{{ node }},{{ ethPre }}/{{ ethPost }},{{ operMode }},{{ operSpeed }},{{ operSt }}
          {% endfor %}
        dest: files/interface_down.csv

    - name: "TASK_6 - 웹엑스 알림"
      cisco_spark:
        recipient_type: roomId
        recipient_id:   "{{ roomID }}"
        message_type:   "markdown"
        personal_token: "{{ bot_token }}"
        msg:            "인터페이스 다운 {{ interface_down | length }}건 확인하시기 바랍니다. - sent by {{ alert_sender }}"

    - name: "TASK_7 - 이메일 알림"
      community.general.mail:
        host:     "{{ outlook_host }}"
        port:     "{{ outlook_port }}"
        username: "{{ outlook_username }}"
        password: "{{ outlook_password }}"
        from:     "{{ outlook_username }}"
        to :      "{{ outlook_receiver }}"
        subject:  "[ACI 자동화 데모] 인터페이스 Oper Stat Down - sent by {{ alert_sender }}"
        subtype:  "html"
        body:     "<center><img width=1000 height=562 src=\"https://storage.googleapis.com/blogs-images/ciscoblogs/1/2020/05/Slide1-1.jpeg\"><h1>Cisco Customer Success는<br>고객 여러분의 성공을 도와드립니다.</h1></center>"
        secure:   "starttls"
        headers:  "Content-type=text/html"
        attach: 
          - files/interface_down.csv