- hosts: apic
  connection: local
  gather_facts: no

  vars:
    apic_info: &apic_info
      host:           "{{ ansible_host }}" 
      user:           "{{ ansible_user }}" 
      password:       "{{ ansible_password }}" 
      validate_certs: "{{ validate_certs }}"
      use_ssl:        "{{ use_ssl }}"

  vars_files: 
    - vars/tenant.yml
    - vars/static_paths.yml

  tasks:
    - name: TASK_1 - remove static ports
      cisco.aci.aci_static_binding_to_epg:
        <<: *apic_info
        state:            absent
        tenant:           "{{ tenant.name }}"
        ap:               "{{ item.ap }}"
        epg:              "{{ item.epg }}"
        encap_id:         "{{ item.encap }}"
        deploy_immediacy: "{{ item.immediacy }}"
        interface_mode:   "{{ item.mode }}"
        interface_type:   "{{ item.type }}"
        pod_id:           "{{ item.pod }}"
        leafs:            "{{ item.leaf }}"
        interface:        "{{ item.interface }}"
      with_items: "{{ static_paths }}"