---
  - name: check tenant - querying
    cisco.aci.aci_tenant:
      host:           "{{ ansible_host }}" 
      user:           "{{ ansible_user }}" 
      password:       "{{ ansible_password }}" 
      validate_certs: "{{ validate_certs }}"
      use_ssl:        "{{ use_ssl }}"
      tenant:         "{{ tenant.name }}"
      state:          "query"
    register: queried_tenant

  - name: check tenant - validate
    ansible.builtin.assert:
      that:     queried_tenant.current
      fail_msg: TENANT_NOT_EXISTS